name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex

    strategy:
      matrix:
        repo:
          - owner: moonhyukjin
            name: final-06-GuDog-release
            token: TOKEN_MHJ
            email: EMAIL_MHJ
          - owner: sooorAyun
            name: final-06-GuDog-release
            token: TOKEN_YSR
            email: EMAIL_YSR
          - owner: byeolscript
            name: final-06-GuDog-release
            token: TOKEN_KEB
            email: EMAIL_KEB
          - owner: tjwngml
            name: final-06-GuDog-release
            token: TOKEN_SJH
            email: EMAIL_SJH

    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets[matrix.repo.token] }}
        with:
          source-directory: 'output'
          destination-github-username: ${{ matrix.repo.owner }}
          destination-repository-name: ${{ matrix.repo.name }}
          user-email: ${{ secrets[matrix.repo.email] }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY